# Generated by Django 4.2.3 on 2023-07-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/categories/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('owner_fullname', models.CharField(max_length=64)),
                ('floor', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
    ]
